version: "3"
services:
  
  master:
    image: mongo
    networks:
      - backend
    deploy:
    #   replicas: 1
      placement:
        constraints: [node.role == manager]
    command: mongod --replSet rs
    

  node1: 
    image: mongo
    networks:
      - backend
    # deploy:
    #   replicas: 1
    command: mongod --replSet rs

  node2: 
    image: mongo
    networks:
      - backend
    # deploy:
    #   replicas: 1
    command: mongod --replSet rs

networks:
  backend: